{
    'name': 'MB Custom Api',
    'category': 'matbao',
    'author': 'Huy Snow',
    'description': 'Custom logic Api class sale oder',
    'depends': [
        'product',
        'resource',
        'mb_customer_promotion',
        'mb_change_order_processing',
        'mb_document_custom',
        'mb_purchase_custom',
        'mb_recruitment',
        'mb_report_sale_order',
        'mb_security',
        'mb_service_review',
        'mb_so_renewed',
        'mb_transaction',
        'mb_transaction_history',
        'mb_service',
        'document_page',
        'sales_team',
        'mb_manage_server',

    ],
    'data': [
        'views/document_page_view.xml',
        'views/product_product_view.xml',
        'views/vnnic_customer_view.xml',
        'views/system_api_view.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
}