from . import account_invoice
from . import external_create_service
from . import external_po
from . import external_so
from . import product_agency_price
from . import product_category
from . import res_partner
from . import reseller_customer
from . import sale_order
from . import sale_order_line
from . import sale_phone_history
from . import sale_service
