{
    'name': 'MB Fix Bugs Milestone 3',
    'category': 'matbao',
    'author': 'vuhai',
    'description': 'Fix bugs',
    'depends': [
        'mb_fix_milestone2',
        'document_page',
        'mb_sale_pipeline',
        'hr_timesheet',
        'hr_holidays_multi_levels_approval',
        'mb_internet_banking',
    ],
    'data': [
        'security/ir_rule.xml',
        'wizards/cost_price_domain_vn.xml',
        'wizards/mail_wizard_invite.xml',
        'wizards/search_service_wizard.xml',
        'views/document_page.xml',
        'views/stock.xml',
        'views/sale_order.xml',
        'views/account_bank_statement.xml',
        'views/vat_invoice.xml',
        'views/crm_lead.xml',
        'views/project.xml',
        'views/sale_service.xml',
        'views/hr_holidays.xml',
        'views/res_partner.xml',
        'views/menu.xml',
    ],
    'installable': True,
}